import chan from '../images/chan.png'
import chanminaNGU from '../images/chanminaNGU.png'

export const artistList = [
    { image: chan, name: "Chanmina" },
    { image: "", name: "Justin Bieber" },
    { image: "", name: "Awich" },
    { image: "", name: "Red Velvet" },
    { image: "", name: "Dreamcatcher" },
    { image: "", name: "The Weeknd" },
    { image: "", name: "Blackpink" },
    { image: "", name: "Yeeun" },
    { image: "", name: "Aespa" },
    { image: "", name: "Purple Kiss" },
    { image: "", name: "Yoasobi" },
    { image: "", name: "Jiu" },
    { image: "", name: "Yuu Shinoda" },
    { image: "", name: "Joyner Lucas" },
    { image: "", name: "Tim" },
    { image: "", name: "Twice" },
    { image: "", name: "BTS" },
]

export const songList = [
    { image: chanminaNGU, name: "Never Grow Up"},
    { image: "", name: "Harenchi"},
    { image: "", name: "In The Flames"},
    { image: "", name: "Bijin"},
    { image: "", name: "Chocolate"},
    { image: "", name: "Angel"},
    { image: "", name: "^.^"},
    { image: "", name: "Period"},
    { image: chanminaNGU, name: "Call"},
    { image: "", name: "King"},
    { image: "", name: "Picky"},
    { image: "", name: "Voice Memo No.5"},
    { image: "", name: "Baby"},
    { image: chanminaNGU, name: "Can U love Me"},
    { image: chanminaNGU, name: "Like This"},
    { image: chanminaNGU, name: "CAFE"},
    { image: "", name: "Sweet Memory"},
    { image: "", name: "Rainy Friday"},
    { image: "", name: "Very Nice To Meet You"},
    { image: "", name: "I Cannot Go Back To You"},
    { image: "", name: "note-book"},
    { image: "", name: "Morning Mood"},
]